### ISSUE TITLE
Publish new version to include lineNumbers functionality

### ISSUE THREAD

**Issue by thekiwi** [BertrandBev/code_field#67]
First off, great library! Thanks for writing & maintaining it! 

I'd like to use the `lineNumbers` visibility toggle you added into `CodeField` but I noticed the package published on pub.dev is a little outdated (most recent version was published around a year ago).

Would you be able to publish a new version with the most recent changes?

**Comment by gumbarros** [comment]
@BertrandBev  I also need a new version because of the ```readOnly```parameter.

**Comment by t-m-z** [comment]
Also from my side: thank you for your great work. But as thewiki commented - I would like to use the lineNumbers visibility toggle you added into CodeField, too.
Thank you in advance.

**Comment by gumbarros** [comment]
Guys if the mainteiner don't respond, should we fork the project and publish to pub.dev?

**Comment by t-m-z** [comment]
This would be a proper solution.
However until now I have never built a package.
I am not such a skilled developer.

regards
Thomas 

Sent from MailDroid

-----Original Message-----

**Comment by gumbarros** [comment]
I will try to email @BertrandBev , if he don't respond until Tuesday, I will create a fork and publish to pub.dev the fixes because I really need the read-only parameter.

**Comment by mack-at-pieces** [comment]
Hi @gumbarros @t-m-z @thekiwi - I understand the frustration here. I don't think it's required that you publish a new version of the package in order to use some of the features you're interested in.

What you can do is create a git dependency in your `pubspec.yaml` and point it to a specific commit, which you'll see is what I've done for my project below. This will give you access to the latest properties that I've also attached.

<img width="379" alt="Screen Shot 2022-10-17 at 8 57 21 AM" src="https://user-images.githubusercontent.com/30325757/196182880-747071e2-0568-4706-b3ba-4165f62dd7bf.png">

<img width="629" alt="Screen Shot 2022-10-17 at 8 59 03 AM" src="https://user-images.githubusercontent.com/30325757/196183276-7f0b9464-7676-4d4e-90b0-d9dc3b2a3173.png">

Happy to help if you run into issues.

**Comment by gumbarros** [comment]
> Hi @gumbarros @t-m-z @thekiwi - I understand the frustration here. I don't think it's required that you publish a new version of the package in order to use some of the features you're interested in.
> 
> What you can do is create a git dependency in your `pubspec.yaml` and point it to a specific commit, which you'll see is what I've done for my project below. This will give you access to the latest properties that I've also attached.
> 
> <img alt="Screen Shot 2022-10-17 at 8 57 21 AM" width="379" src="https://user-images.githubusercontent.com/30325757/196182880-747071e2-0568-4706-b3ba-4165f62dd7bf.png">
> 
> <img alt="Screen Shot 2022-10-17 at 8 59 03 AM" width="629" src="https://user-images.githubusercontent.com/30325757/196183276-7f0b9464-7676-4d4e-90b0-d9dc3b2a3173.png">
> 
> Happy to help if you run into issues.

Genius, thanks!

**Comment by BertrandBev** [comment]
Hey @gumbarros & @thekiwi,
Sorry for my lack of reactivity lately. I have a bunch on my plate, but I'll try to publish a new version sometimes tomorrow. In the meantime, @mack-at-pieces answer is definitely the way to go!
